spring:
  #本地
  profiles:
    active: local
  application:
    name: ym-blog-backEnd
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ym-blog
    username: root
    password: yunmao
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 18000


    # redis
  redis:
    host: 127.0.0.1     # Redis服务器地址
    port: 6379          # Redis服务器连接端口
    password:     # Redis服务器连接密码（默认为空）
    database: 1         # Redis数据库索引（默认为0）
    timeout: 60s        # 连接空闲超过N(s秒、ms毫秒，不加单位时使用毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
    # Lettuce连接池配置
    lettuce:
      pool:
        max-active: 10  # 允许最大连接数，默认8（负值表示没有限制），推荐值：大于cpu * 2，通常为(cpu * 2) + 2
        max-idle: 8     # 最大空闲连接数，默认8，推荐值：cpu * 2
        min-idle: 0     # 最小空闲连接数，默认0
        max-wait: 5s    # 连接用完时，新的请求等待时间(s秒、ms毫秒)，超过该时间抛出异常，默认-1（负值表示没有限制）


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.ym.blogBackEnd.controller


# 自己的 一些配置
ym:
  # 密码 加盐
  encrypt: YunMao
  # 默认 密码
  default-password: 1234567890
  # 账号长度 最小值
  account-length : 8
  # 密码长度 最小值
  password-length: 8
  # 发送邮件
  emailFrom: 1761230164@qq.com




